### ISSUE TITLE
Iniciar manual de usuario y técnico 

### ISSUE THREAD

**Issue by nelsoncaastro** [BigDreamsCoders/Tremor#12]
Hay que utilizar la misma funcionalidad de Wiki del repositorio

**Comment by nelsoncaastro** [comment]
Comenzado el manual técnico, ahorita agregando explicación sobre el algoritmo de Random Forest Regression.

**Comment by anquim** [comment]
Se ha concluido con el manual de usuario

**Comment by petrlr14** [comment]
Creo que esta completo!
