### ISSUE TITLE
Rediseño de input fields 

### ISSUE THREAD

**Issue by nelsoncaastro** [BigDreamsCoders/Tremor#3]
Vamos a cambiar los inputs que utilizamos en el modelomatematico, por lo cual necesitamos un rediseño de la UI.

**Comment by petrlr14** [comment]
Luego de una sesión exhaustante llegamos a este precioso diseño, muchas gracias @nelsoncaastro y @henrybanchon3 !
![Mockup_pirata](https://user-images.githubusercontent.com/31825365/87235576-93c89f00-c39a-11ea-87ce-ca194dd9acc3.png)
